insert into departamento (NMDEPARTAMENTO) values ('Celulares e Telefones');
insert into produto (cdDepartamento, dsProduto) values (1, 'lg k22');
insert into produto (cdDepartamento, dsProduto) values (1, 'carregador tubo motorola');
insert into produto (cdDepartamento, dsProduto) values (1, 'iphone xr');
insert into produto (cdDepartamento, dsProduto) values (1, 'lg k9');
insert into produto (cdDepartamento, dsProduto) values (1, 'headset 7.1');
insert into produto (cdDepartamento, dsProduto) values (1, 'samsung j8');
insert into produto (cdDepartamento, dsProduto) values (1, 'smartwatch xiaomi');
insert into produto (cdDepartamento, dsProduto) values (1, 'xiaomi mi9');
insert into produto (cdDepartamento, dsProduto) values (1, 'samsung j5');
insert into produto (cdDepartamento, dsProduto) values (1, 'celular xiaomi mi9');
insert into produto (cdDepartamento, dsProduto) values (1, 'bateria de moto');
insert into produto (cdDepartamento, dsProduto) values (1, 'galaxy s9');
insert into produto (cdDepartamento, dsProduto) values (1, 'moto g3');
insert into produto (cdDepartamento, dsProduto) values (1, 'fone samsung original');
insert into produto (cdDepartamento, dsProduto) values (1, 'cabo otg');
insert into produto (cdDepartamento, dsProduto) values (1, 'fone iphone');
insert into produto (cdDepartamento, dsProduto) values (1, 'google pixel');
insert into produto (cdDepartamento, dsProduto) values (1, 'smartwatch iwo w46');

insert into departamento (NMDEPARTAMENTO) values ('Eletrônicos, Áudio e Vídeo');
insert into produto (cdDepartamento, dsProduto) values (2, 'projetor epson');
insert into produto (cdDepartamento, dsProduto) values (2, 'tv lg 43');
insert into produto (cdDepartamento, dsProduto) values (2, 'mesa digital');
insert into produto (cdDepartamento, dsProduto) values (2, 'tv box tx9');
insert into produto (cdDepartamento, dsProduto) values (2, 'rádio relógio digital');
insert into produto (cdDepartamento, dsProduto) values (2, 'btvb 11');
insert into produto (cdDepartamento, dsProduto) values (2, 'mp4 player');
insert into produto (cdDepartamento, dsProduto) values (2, 'fonte 12v');
insert into produto (cdDepartamento, dsProduto) values (2, 'caixa de som jbl boombox');
insert into produto (cdDepartamento, dsProduto) values (2, 'tvbox mxqpro');
insert into produto (cdDepartamento, dsProduto) values (2, 'caixa de som para tv');
insert into produto (cdDepartamento, dsProduto) values (2, 'sky solo plus');
insert into produto (cdDepartamento, dsProduto) values (2, 'placa amplificada');
insert into produto (cdDepartamento, dsProduto) values (2, 'mini system');
insert into produto (cdDepartamento, dsProduto) values (2, 'alexa');
insert into produto (cdDepartamento, dsProduto) values (2, 'tv 42');
insert into produto (cdDepartamento, dsProduto) values (2, 'smart tv');
insert into produto (cdDepartamento, dsProduto) values (2, 'controle samsung smart');

insert into departamento (NMDEPARTAMENTO) values ('Informática');
insert into produto (cdDepartamento, dsProduto) values (3, 'modem 4g');
insert into produto (cdDepartamento, dsProduto) values (3, 'rtx 280');
insert into produto (cdDepartamento, dsProduto) values (3, 'case hd externo');
insert into produto (cdDepartamento, dsProduto) values (3, 'teclado redragon');
insert into produto (cdDepartamento, dsProduto) values (3, 'monitor full hd');
insert into produto (cdDepartamento, dsProduto) values (3, 'hd notebook 500gb');
insert into produto (cdDepartamento, dsProduto) values (3, 'memória ram');
insert into produto (cdDepartamento, dsProduto) values (3, 'memória ddr2');
insert into produto (cdDepartamento, dsProduto) values (3, 'pendrive 8gb');
insert into produto (cdDepartamento, dsProduto) values (3, 'mouse redragon');
insert into produto (cdDepartamento, dsProduto) values (3, 'teclado semi mecânico');
insert into produto (cdDepartamento, dsProduto) values (3, 'torre de tomada');
insert into produto (cdDepartamento, dsProduto) values (3, 'impressora laser');
insert into produto (cdDepartamento, dsProduto) values (3, 'mini teclado wireless');
insert into produto (cdDepartamento, dsProduto) values (3, 'watercooler');
insert into produto (cdDepartamento, dsProduto) values (7, 'headset hyperx');
insert into produto (cdDepartamento, dsProduto) values (7, 'teclado e mouse para celular');
insert into produto (cdDepartamento, dsProduto) values (7, 'memória ram ddr4');
insert into produto (cdDepartamento, dsProduto) values (7, 'i3 9100f');

insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Allison Flaviana Ferreira',                   to_date('22/01/1997', 'DD/MM/YYYY'), to_date('25/04/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Sérgio E Filho',                              to_date('29/05/1984', 'DD/MM/YYYY'), to_date('14/07/2023', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Dra Andréia Corona de Dávila',                to_date('23/09/1981', 'DD/MM/YYYY'), to_date('05/09/2021', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Lara e Léia LTDA',                            to_date('23/04/1978', 'DD/MM/YYYY'), to_date('27/11/2022', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Ricardo Franco de Ferreira',                  to_date('05/02/1989', 'DD/MM/YYYY'), to_date('20/05/2019', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('José Túlio Bezerra Sobrinho',                 to_date('10/05/2002', 'DD/MM/YYYY'), to_date('08/01/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Dante Elano Branco de Galhardo',              to_date('14/12/1978', 'DD/MM/YYYY'), to_date('21/04/2014', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Pedro Max de Barreto Sobrinho',               to_date('24/10/1984', 'DD/MM/YYYY'), to_date('03/04/2016', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Psicóloga Cármen Rute Fidalgo de Uchoa',      to_date('03/08/1980', 'DD/MM/YYYY'), to_date('08/03/2023', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Vicente Lutero Filho',                        to_date('24/12/1990', 'DD/MM/YYYY'), to_date('28/10/2014', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Salão de Beleza Ayra Bella',                  to_date('13/10/1992', 'DD/MM/YYYY'), to_date('06/01/2011', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Grace Ayane Almeida',                         to_date('20/06/1999', 'DD/MM/YYYY'), to_date('22/12/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Bingre LTDA',                                 to_date('25/10/2007', 'DD/MM/YYYY'), to_date('11/08/2019', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Lara Capucho Jamandas',                       to_date('06/11/2000', 'DD/MM/YYYY'), to_date('09/11/2010', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Maria Yonara Covilhã de Galindo',             to_date('04/04/1976', 'DD/MM/YYYY'), to_date('29/07/2023', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Carmen Damiana Coutinho',                     to_date('03/05/2003', 'DD/MM/YYYY'), to_date('06/03/2011', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Violeta Castilho de Homem',                   to_date('02/10/2003', 'DD/MM/YYYY'), to_date('14/09/2015', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Kelly Irina de Bonito',                       to_date('13/05/1975', 'DD/MM/YYYY'), to_date('08/03/2014', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Liliana Cloé Abreu de Perdigão',              to_date('11/06/1981', 'DD/MM/YYYY'), to_date('03/11/2017', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Eloá Noémi Cabral Ferreira Murtinho',         to_date('15/04/2003', 'DD/MM/YYYY'), to_date('21/05/2013', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Irmãos Lucas',                                to_date('02/12/2004', 'DD/MM/YYYY'), to_date('02/10/2022', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Isaac Cancela Fortes',                        to_date('11/09/1987', 'DD/MM/YYYY'), to_date('30/07/2014', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Nelson Jesus de Carvalho',                    to_date('22/04/1977', 'DD/MM/YYYY'), to_date('27/07/2016', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Jaime Barreto de Mena',                       to_date('17/10/1982', 'DD/MM/YYYY'), to_date('14/07/2015', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('João Fernando Jesus Esteves',                 to_date('22/09/1992', 'DD/MM/YYYY'), to_date('03/08/2011', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Manuel Empreendimentos',                      to_date('04/01/1975', 'DD/MM/YYYY'), to_date('11/05/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Família Rios',                                to_date('16/07/1990', 'DD/MM/YYYY'), to_date('13/08/2014', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Luís Araújo',                                 to_date('23/06/2006', 'DD/MM/YYYY'), to_date('05/10/2014', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Kevin Thiago Arantes de Bulhosa',             to_date('05/08/1979', 'DD/MM/YYYY'), to_date('16/09/2017', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Clube Vasco Motocross',                       to_date('24/02/1984', 'DD/MM/YYYY'), to_date('23/04/2012', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Renato Domingos Banha Magalhães',             to_date('01/01/1987', 'DD/MM/YYYY'), to_date('12/10/2013', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Rodrigo Leandro Pacheco Sabrosa Vargas',      to_date('08/03/2004', 'DD/MM/YYYY'), to_date('27/07/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('José Diego Lopes Abasto Carregueiro',         to_date('20/06/1997', 'DD/MM/YYYY'), to_date('05/09/2017', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('PetShop Belém',                               to_date('27/03/1997', 'DD/MM/YYYY'), to_date('27/09/2015', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Artur Salvador Mamouros Medeiros Regalado',   to_date('14/04/1991', 'DD/MM/YYYY'), to_date('12/12/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Matias Lucas Bivar Pereira Ruas',             to_date('19/11/1983', 'DD/MM/YYYY'), to_date('09/02/2013', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('António Mota de Alcaide',                     to_date('14/06/2001', 'DD/MM/YYYY'), to_date('26/02/2019', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Matias Davi de Borges',                       to_date('09/12/1976', 'DD/MM/YYYY'), to_date('22/04/2011', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Noah Igor Brochado Gravato Paz',              to_date('24/08/2006', 'DD/MM/YYYY'), to_date('04/01/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Matheus Bettencourt de Cipriano',             to_date('07/09/1984', 'DD/MM/YYYY'), to_date('04/09/2013', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Vicente Flávio Colaço Ferreira Sítima',       to_date('11/02/2003', 'DD/MM/YYYY'), to_date('24/03/2023', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Mário José de Faia',                          to_date('08/04/2005', 'DD/MM/YYYY'), to_date('14/09/2014', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Dinis Mário de Passarinho',                   to_date('13/03/2005', 'DD/MM/YYYY'), to_date('01/05/2013', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Ângelo Kelvin Flávio Monte Quinteiro',        to_date('18/01/1981', 'DD/MM/YYYY'), to_date('19/06/2017', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Agropecuária Dutra',                          to_date('22/08/2004', 'DD/MM/YYYY'), to_date('14/12/2010', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Francielle Lira',                             to_date('25/07/2006', 'DD/MM/YYYY'), to_date('08/08/2011', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Leonara Assunção de Junqueira',               to_date('07/01/1979', 'DD/MM/YYYY'), to_date('15/08/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Leonara Suzanne de Beltrão',                  to_date('19/01/1983', 'DD/MM/YYYY'), to_date('04/06/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Amália Corona',                               to_date('13/02/1978', 'DD/MM/YYYY'), to_date('15/11/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Fernanda Madeira Sandoval',                   to_date('06/05/1992', 'DD/MM/YYYY'), to_date('12/12/2018', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Aaron Manuel de Leon',                        to_date('16/04/1997', 'DD/MM/YYYY'), to_date('13/04/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Adriana Ainoa Almada de Paulos',              to_date('22/06/1989', 'DD/MM/YYYY'), to_date('01/09/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Adriana Benisha de Gois',                     to_date('13/09/1990', 'DD/MM/YYYY'), to_date('11/06/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Adriana Ketlin Estrada de Franco',            to_date('27/11/2007', 'DD/MM/YYYY'), to_date('09/12/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Adriano Casanova Jr.',                        to_date('02/09/2001', 'DD/MM/YYYY'), to_date('24/10/2021', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Adriano Cervantes Sobrinho',                  to_date('09/07/2003', 'DD/MM/YYYY'), to_date('04/04/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Afonso Igor Nunes Colaço',                    to_date('11/02/2005', 'DD/MM/YYYY'), to_date('27/06/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Agustina Galhardo de Braga',                  to_date('06/08/2006', 'DD/MM/YYYY'), to_date('04/02/2023', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Aisha Siara Bilhalva de Jardim',              to_date('18/06/1996', 'DD/MM/YYYY'), to_date('04/12/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Aldo Samuel Matias Sobrinho',                 to_date('27/05/1992', 'DD/MM/YYYY'), to_date('24/04/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Alessandra Ávila de Beltrão',                 to_date('01/12/2006', 'DD/MM/YYYY'), to_date('30/12/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Alessandra Brito',                            to_date('08/10/1988', 'DD/MM/YYYY'), to_date('07/12/2020', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Alfredo Lutero Reis',                         to_date('12/02/1987', 'DD/MM/YYYY'), to_date('21/05/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Alícia Anna Ginjeira de Peçanha',             to_date('26/06/1994', 'DD/MM/YYYY'), to_date('29/03/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Aliyah Damásio de Negreiros',                 to_date('18/04/2007', 'DD/MM/YYYY'), to_date('20/09/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Álvaro Sebastian de Azevedo',                 to_date('10/12/1991', 'DD/MM/YYYY'), to_date('27/02/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Amanda Jéssica Marinho de Uchoa',             to_date('16/03/2001', 'DD/MM/YYYY'), to_date('28/01/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Ana Margarida de Ferraz',                     to_date('31/03/1990', 'DD/MM/YYYY'), to_date('11/10/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Ana Marilúcia de Molina',                     to_date('14/05/1996', 'DD/MM/YYYY'), to_date('26/03/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('André Álvaro Macena de Marcondes',            to_date('18/06/1999', 'DD/MM/YYYY'), to_date('06/11/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('André Artur Jimenes Maldonado',               to_date('24/10/1996', 'DD/MM/YYYY'), to_date('19/01/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('André Raul Protásio Santos Sobreira',         to_date('30/12/2000', 'DD/MM/YYYY'), to_date('06/09/2023', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('André Torres Sardinha',                       to_date('10/12/1988', 'DD/MM/YYYY'), to_date('15/03/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Andrei Félix Azenha de Barrela',              to_date('22/05/1995', 'DD/MM/YYYY'), to_date('23/12/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Andres Gonçalves Sobrinho',                   to_date('05/09/1990', 'DD/MM/YYYY'), to_date('14/09/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Andressa Jandira Carrara Espinoza',           to_date('16/12/2002', 'DD/MM/YYYY'), to_date('31/03/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Angélica Galvão',                             to_date('04/06/2001', 'DD/MM/YYYY'), to_date('23/08/2020', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Ângelo Benites Neto',                         to_date('03/10/1988', 'DD/MM/YYYY'), to_date('06/09/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Artur Lourenço Cangueiro de Gois',            to_date('08/06/2006', 'DD/MM/YYYY'), to_date('21/05/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Augusto Gilberto Aguiar de Delvalle',         to_date('10/08/1989', 'DD/MM/YYYY'), to_date('02/03/2023', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Ayrton Carlos Cruz Ferreira',                 to_date('04/09/2001', 'DD/MM/YYYY'), to_date('14/03/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Beatriz Margarete Barros Franco',             to_date('27/08/2000', 'DD/MM/YYYY'), to_date('11/08/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Benedito Wagner Assunção',                    to_date('18/09/1995', 'DD/MM/YYYY'), to_date('12/02/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Berenice Marli Leal de Álvares',              to_date('18/12/2004', 'DD/MM/YYYY'), to_date('09/10/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Beto Chico de Bezerra',                       to_date('05/08/1990', 'DD/MM/YYYY'), to_date('14/12/2020', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Bruna Rebeca Pinto de Rijo',                  to_date('02/08/2000', 'DD/MM/YYYY'), to_date('21/11/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Bruna Soares de Calçada',                     to_date('20/02/1997', 'DD/MM/YYYY'), to_date('10/04/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Bruno Roberto de Melo',                       to_date('28/11/2001', 'DD/MM/YYYY'), to_date('04/08/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Carla Beatriz Rivera de Serna',               to_date('09/11/1998', 'DD/MM/YYYY'), to_date('11/11/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Carlos Kelvin de Galvão',                     to_date('30/09/2004', 'DD/MM/YYYY'), to_date('16/12/2022', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Carlos Leite',                                to_date('25/05/1988', 'DD/MM/YYYY'), to_date('01/04/2021', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Carlos Reginaldo Furtado de Barbosa',         to_date('14/07/2005', 'DD/MM/YYYY'), to_date('24/03/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Cecília Barros Furtado',                      to_date('13/03/2007', 'DD/MM/YYYY'), to_date('25/04/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Celeste Barreto',                             to_date('27/12/1994', 'DD/MM/YYYY'), to_date('08/05/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Clara Melanie Assunção',                      to_date('18/09/2002', 'DD/MM/YYYY'), to_date('11/10/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Clarice Svetlana Miranda de Domingos',        to_date('09/07/2000', 'DD/MM/YYYY'), to_date('22/10/2021', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Cléber Perez de Ferraz',                      to_date('08/09/1990', 'DD/MM/YYYY'), to_date('06/08/2020', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Concha Miria de Catela',                      to_date('03/09/1987', 'DD/MM/YYYY'), to_date('23/12/2020', 'DD/MM/YYYY'), 'J');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Cristiana Amaro de Damásio',                  to_date('31/12/2001', 'DD/MM/YYYY'), to_date('01/01/2023', 'DD/MM/YYYY'), 'F');
insert into pessoa (nmPessoa, dtNascimento, dtCadastro, tpPessoa) values ('Cristiano Wellington de Domingues Jr.',       to_date('14/07/2006', 'DD/MM/YYYY'), to_date('11/04/2020', 'DD/MM/YYYY'), 'F');
