SELECT NOTA.NUMERO, NOTA.VALOR,
       SUM(NOTA.VALOR) OVER (PARTITION BY NULL 
                             ORDER BY NOTA.NUMERO
                             ROWS BETWEEN UNBOUNDED PRECEDING AND 0 PRECEDING) AS SALDOATUAL
  FORM NOTA_FISCAL NOTA
  